spring:
  datasource:
    name: DataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/snn_article?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  session:
    timeout: 1800 # 单位秒
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  # mapper映射文件路径
logging:
  level:
    com.snn.article.dao: debug # 可以在日志中看到sql语句
